use prost::Message;
use tonic_reflection::server::Builder as ReflectionBuilder;

pub mod news {
    tonic::include_proto!("news"); // The package name specified in your .proto
    pub(crate) const FILE_DESCRIPTOR_SET: &[u8] =
        tonic::include_file_descriptor_set!("news_descriptor");
}

use news::{News, NewsId, NewsList};

// Round-trips a proto message through the prost codec generated by the upgraded
// prost/tonic-build toolchain. Encoding and decoding back must be lossless.
#[test]
fn proto_roundtrip() {
    let news = News {
        id: 7,
        title: "Note 7".into(),
        body: "Content 7".into(),
        post_image: "Post image 7".into(),
        status: 1,
    };

    let mut buf = Vec::new();
    news.encode(&mut buf).unwrap();
    let decoded = News::decode(buf.as_slice()).unwrap();

    assert_eq!(news, decoded);
}

// Default / empty-field message must survive the round-trip too: proto3 omits
// zero-valued fields on the wire, so an all-default message encodes to no bytes
// and decodes back to the same default value.
#[test]
fn proto_roundtrip_default() {
    let empty = News::default();

    let mut buf = Vec::new();
    empty.encode(&mut buf).unwrap();
    assert!(buf.is_empty());

    let decoded = News::decode(buf.as_slice()).unwrap();
    assert_eq!(empty, decoded);
}

// Nested repeated messages (NewsList { news: [...] }) must round-trip, exercising
// the repeated-field codegen of the upgraded toolchain.
#[test]
fn news_list_roundtrip() {
    let list = NewsList {
        news: vec![
            News {
                id: 1,
                title: "Note 1".into(),
                body: "Content 1".into(),
                post_image: "Post image 1".into(),
                status: 0,
            },
            News {
                id: 2,
                title: "Note 2".into(),
                body: "Content 2".into(),
                post_image: "Post image 2".into(),
                status: 1,
            },
        ],
    };

    let mut buf = Vec::new();
    list.encode(&mut buf).unwrap();
    let decoded = NewsList::decode(buf.as_slice()).unwrap();

    assert_eq!(list, decoded);
    assert_eq!(decoded.news.len(), 2);
    assert_eq!(decoded.news[1].id, 2);
}

// The reflection service is registered in `bind` via the v1 builder API
// (`build_v1`) introduced by the upgraded tonic-reflection. Building it from the
// generated descriptor set must succeed without panicking, proving the embedded
// `news_descriptor` is valid and the new API path is wired correctly.
#[test]
fn reflection_descriptor_builds_v1() {
    ReflectionBuilder::configure()
        .register_encoded_file_descriptor_set(news::FILE_DESCRIPTOR_SET)
        .build_v1()
        .unwrap();
}

// Sanity-check a scalar request type used by the service so the generated module
// is exercised end-to-end (not just the message structs above).
#[test]
fn news_id_roundtrip() {
    let id = NewsId { id: 42 };

    let mut buf = Vec::new();
    id.encode(&mut buf).unwrap();
    let decoded = NewsId::decode(buf.as_slice()).unwrap();

    assert_eq!(decoded.id, 42);
}
